---
title: "Getting basin share of days"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output: github_document
---

```{r setup, message=FALSE, include = FALSE}
knitr::opts_chunk$set(comment = NA)
```

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
svy <- readRDS("../data-work/1-svy/svy-final.rds")
svy$basin <- svy$basin %>%
    left_join(select(svy$person, Vrid, weight))
```

## Calculate Share

```{r}
# basinRate(AB): basin rate for activity participants
rate <- svy$basin %>%
    group_by(act, basin, part_water) %>%
    summarise(wtn = sum(weight)) %>%
    mutate(part_rate = wtn / sum(wtn)) %>%
    filter(part_water == "Checked")

# avgDays(AB): average basin days (for those who visit the basin)
avgDays <- svy$basin %>%
    filter(!is.na(days_water), part_water == "Checked") %>%
    group_by(act, basin) %>%
    summarise(avgDays = weighted.mean(days_water, weight), n = n())

# daysShare(AB): share of activity days for each basin
# - so spend(AB) = spend(A) * daysShare(AB)
share <- avgDays %>%
    left_join(select(rate, act, basin, part_rate)) %>%
    mutate(
        days_per_participant = avgDays * part_rate,
        share = days_per_participant / sum(days_per_participant)
    )
```

## Plot

```{r}
share %>%
    ggplot(aes(basin, share)) +
    geom_col() +
    coord_flip() +
    facet_wrap(~ act)
```

## Check

```{r}
summarise(share, sum(share)) %>%
    knitr::kable(caption = "Check sums")
share %>%
    select(act, basin, n) %>%
    spread(act, n, fill = 0) %>%
    knitr::kable(caption = "Sample size")
```

## Profile Table

```{r}
knitr::kable(share)
```

