---
title: "Summarize CO survey weighting"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output: github_document
---

```{r setup, message=FALSE, include = FALSE}
knitr::opts_chunk$set(comment = NA)
```

```{r, message = FALSE}
library(tidyverse)
source("../../R/results.R")
svy_data <- readRDS("../../data/processed/svy.rds")$person
pop_data <- readRDS("../../data/interim/oia-co.rds") %>% filter(in_co_pop)

# use "Other" for third race category
recode_race <- function(df) {
    mutate(df, race_weight = recode_factor(race_weight, `Not white or Hispanic` = "Other") %>%
               factor(levels = c("White", "Hispanic", "Other")))
}
svy_data <- recode_race(svy_data)
pop_data <- recode_race(pop_data)
```

## Weight Summary

```{r}
summary(svy_data$weight)
sd(svy_data$weight)
```

## Representation

There was a small amount of skew between the CO survey (valid) respondents and the target population defined using the OIA survey dataset:

```{r}
figs <- list(
    compare_demo(age_weight, svy_data, pop_data) %>% plot_demo(age_weight, "Age"),
    compare_demo(race_weight, svy_data, pop_data) %>% plot_demo(race_weight, "Race"),
    compare_demo(sex, svy_data, pop_data) %>% plot_demo(sex, "Gender"),
    compare_demo(income_weight, svy_data, pop_data) %>% plot_demo(income_weight, "Income")
)
f1 <- cowplot::plot_grid(figs[[1]], figs[[2]], rel_widths = c(0.5, 0.5), ncol = 2)
f2 <- cowplot::plot_grid(figs[[3]], figs[[4]], rel_widths = c(0.3, 0.7), ncol = 2)

# legend
f3 <- compare_demo(sex, svy_data, pop_data) %>% 
    plot_demo(sex, "", hide_legend = FALSE) %>%
    get_legend() %>%
    cowplot::plot_grid()

figs_out <- cowplot::plot_grid(f1, f2, f3, nrow = 3, rel_heights = c(0.4, 0.4, 0.1))
ggsave("../../out/fig/demorep.png", figs_out, width = 6.5, height = 4.5, units = "in")
figs_out
```

### Survey

```{r}
wt_vars <- c("age_weight", "sex", "income_weight", "race_weight")
sapply(wt_vars, function(x) weights::wpct(svy_data[[x]]))
```

### Target Pop

```{r}
sapply(wt_vars, function(x) weights::wpct(pop_data[[x]], pop_data$stwt))
```

